#' `calibrate`
#' `cohortData`
#' `cohortDefinitionCols`
#' `currentTime`
#' `inactivePixelIndex`
#' `initialB`
#' `pixelGroupMap`
#' `postFireRegenSummary`
#' `rasterToMatch`
#' `rstCurrentBurn`
#' `species`
#' `speciesEcoregion`
#' `successionTimestep`
#' `sufficientLight`
#' `verbose`
