## covr::in_covr() without taking a dependency on covr being installed.
covr_is_running <- function() identical(Sys.getenv("R_COVR"), "true")

test_that("source normalization ignores comments and formatting", {
  ## This is the property the artifact manifest relies on: roxygen edits and
  ## reformatting must not flag committed artifacts as stale, but a real change
  ## to the code must.
  a <- function(x) {
    x + 1
  }
  b <- function(x) {
    ## a comment that should not matter
    x + 1 ## nor this one
  }
  d <- function(x) {
    x + 2
  }

  expect_identical(LandR:::.normalize_src(a), LandR:::.normalize_src(b))
  expect_false(identical(LandR:::.normalize_src(a), LandR:::.normalize_src(d)))
})

test_that("artifact hashes are deterministic and cover the documented functions", {
  testthat::skip_if_not_installed("digest")

  hashes <- LandR:::.artifact_hashes()

  expect_named(hashes, "counts")
  expect_identical(hashes, LandR:::.artifact_hashes())

  ## every named function must actually exist in the namespace, otherwise the
  ## manifest silently stops guarding it
  for (fns in LandR:::.artifact_fns) {
    for (nm in fns) {
      expect_true(
        is.function(get0(nm, envir = asNamespace("LandR"), ifnotfound = NULL)),
        info = paste0("`", nm, "` listed in .artifact_fns but not found in LandR")
      )
    }
  }

  ## the statistics are recomputed at vignette build time, so they must not
  ## gate the (expensive) counts table
  expect_false("stats_from_counts" %in% LandR:::.artifact_fns$counts)
  expect_false("weighted_quantile" %in% LandR:::.artifact_fns$counts)
})

test_that("committed vignette artifacts are not stale", {
  testthat::skip_if_not_installed("digest")

  ## covr rewrites every function body in R/ to insert trace counters, so the
  ## normalized source it sees is not the source that produced the artifacts and
  ## the hash cannot match. Nothing is lost by skipping: the R CMD check legs run
  ## this test against uninstrumented code.
  testthat::skip_if(covr_is_running(), "function bodies are instrumented under covr")

  manifest <- LandR:::.read_artifact_manifest()
  testthat::skip_if(
    is.null(manifest),
    "vignette artifacts not generated; run data-raw/precompute-vignettes.R"
  )

  hashes <- LandR:::.artifact_hashes()

  expect_identical(
    manifest$counts_hash,
    unname(hashes[["counts"]]),
    label = paste(
      "The committed counts table in inst/extdata/ was generated by different",
      "code than is in R/ now, so the vignette's national statistics are stale.",
      "Regenerate with data-raw/precompute-vignettes.R (needs the national",
      "rasters), or ask a maintainer to."
    )
  )

})
