// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pixelUnifCpp
NumericVector pixelUnifCpp(NumericVector x, NumericVector y, double resx, double resy);
RcppExport SEXP _LandR_pixelUnifCpp(SEXP xSEXP, SEXP ySEXP, SEXP resxSEXP, SEXP resySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type resx(resxSEXP);
    Rcpp::traits::input_parameter< double >::type resy(resySEXP);
    rcpp_result_gen = Rcpp::wrap(pixelUnifCpp(x, y, resx, resy));
    return rcpp_result_gen;
END_RCPP
}
// spiralLoopCpp
List spiralLoopCpp(IntegerVector pixelIndex_in, IntegerVector speciesCode_in, IntegerVector rowOrig_in, IntegerVector colOrig_in, IntegerVector seeddist_max_perRow, IntegerVector spiralRow, IntegerVector spiralCol, NumericVector spiralCurDist, int pgmRows, int pgmCols, IntegerVector pgv, IntegerVector srcPg, IntegerVector srcSpeciesCode, int numSp, NumericMatrix wardProbByDist, NumericVector activeSpMaxDist, NumericVector activeSpMax, double cellSize, int successionTimestep, int verbose, bool wardAlreadyExp, bool debug);
RcppExport SEXP _LandR_spiralLoopCpp(SEXP pixelIndex_inSEXP, SEXP speciesCode_inSEXP, SEXP rowOrig_inSEXP, SEXP colOrig_inSEXP, SEXP seeddist_max_perRowSEXP, SEXP spiralRowSEXP, SEXP spiralColSEXP, SEXP spiralCurDistSEXP, SEXP pgmRowsSEXP, SEXP pgmColsSEXP, SEXP pgvSEXP, SEXP srcPgSEXP, SEXP srcSpeciesCodeSEXP, SEXP numSpSEXP, SEXP wardProbByDistSEXP, SEXP activeSpMaxDistSEXP, SEXP activeSpMaxSEXP, SEXP cellSizeSEXP, SEXP successionTimestepSEXP, SEXP verboseSEXP, SEXP wardAlreadyExpSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type pixelIndex_in(pixelIndex_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type speciesCode_in(speciesCode_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rowOrig_in(rowOrig_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type colOrig_in(colOrig_inSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type seeddist_max_perRow(seeddist_max_perRowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spiralRow(spiralRowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spiralCol(spiralColSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spiralCurDist(spiralCurDistSEXP);
    Rcpp::traits::input_parameter< int >::type pgmRows(pgmRowsSEXP);
    Rcpp::traits::input_parameter< int >::type pgmCols(pgmColsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pgv(pgvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type srcPg(srcPgSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type srcSpeciesCode(srcSpeciesCodeSEXP);
    Rcpp::traits::input_parameter< int >::type numSp(numSpSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type wardProbByDist(wardProbByDistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type activeSpMaxDist(activeSpMaxDistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type activeSpMax(activeSpMaxSEXP);
    Rcpp::traits::input_parameter< double >::type cellSize(cellSizeSEXP);
    Rcpp::traits::input_parameter< int >::type successionTimestep(successionTimestepSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type wardAlreadyExp(wardAlreadyExpSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(spiralLoopCpp(pixelIndex_in, speciesCode_in, rowOrig_in, colOrig_in, seeddist_max_perRow, spiralRow, spiralCol, spiralCurDist, pgmRows, pgmCols, pgv, srcPg, srcSpeciesCode, numSp, wardProbByDist, activeSpMaxDist, activeSpMax, cellSize, successionTimestep, verbose, wardAlreadyExp, debug));
    return rcpp_result_gen;
END_RCPP
}
// windowCountsByClassCpp
IntegerMatrix windowCountsByClassCpp(IntegerVector lccVals, IntegerVector candClasses, int nrow, int ncol, IntegerVector cells0, IntegerVector kx, IntegerVector ky);
RcppExport SEXP _LandR_windowCountsByClassCpp(SEXP lccValsSEXP, SEXP candClassesSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP cells0SEXP, SEXP kxSEXP, SEXP kySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type lccVals(lccValsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type candClasses(candClassesSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cells0(cells0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type kx(kxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ky(kySEXP);
    rcpp_result_gen = Rcpp::wrap(windowCountsByClassCpp(lccVals, candClasses, nrow, ncol, cells0, kx, ky));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LandR_pixelUnifCpp", (DL_FUNC) &_LandR_pixelUnifCpp, 4},
    {"_LandR_spiralLoopCpp", (DL_FUNC) &_LandR_spiralLoopCpp, 22},
    {"_LandR_windowCountsByClassCpp", (DL_FUNC) &_LandR_windowCountsByClassCpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_LandR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
