# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_naInteger <- function(x) {
    .Call('_LandR_is_naInteger', PACKAGE = 'LandR', x)
}

