# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

which2 <- function(x) {
    .Call('_LandR_which2', PACKAGE = 'LandR', x)
}

#' Multiplies two doubles
#'
#' @param cellCoords Matrix, 2 columns, of x-y coordinates of the Receive cells
#' @param overallMaxDist The maximum distance to test for seed dispersal
#' @return A list.
#' @export
spiralSeedDispersal <- function(cellCoords, speciesVectorsList, rcvSpeciesByIndex, speciesTable, numCols, numCells, cellSize, xmin, ymin, k, b, successionTimestep) {
    .Call('_LandR_spiralSeedDispersal', PACKAGE = 'LandR', cellCoords, speciesVectorsList, rcvSpeciesByIndex, speciesTable, numCols, numCells, cellSize, xmin, ymin, k, b, successionTimestep)
}

