utils::globalVariables(c(
  ".data", "Value", "Count", "BinStart", "x", "y"))

#' Generate Summary Figures for Raster Data by Polygon
#'
#' This function creates and saves figures for each polygon in a vector layer,
#' including a histogram of raster values, a map of raster values within the polygon,
#' and a summary of statistics (min, max, median, mean, 25th percentile, 75th percentile,
#' and proportion of zeroes). Optionally, zero values can be removed from the analysis,
#' and the raster can be aggregated to a lower resolution to speed up plotting.
#'
#' @param raster SpatRaster. The raster containing values to be summarized.
#' @param polygons SpatVector or sf object. The vector layer containing polygons.
#' @param counts_df Data frame. A dataframe with counts of raster values per
#' polygon, such as generated by terra::extract. Polygon ID must match that from polygons.
#' @param reference_polygon Optional. SpatVector or sf object. A polygon used
#' as a reference map for inset plotting.
#' @param output_dir Character. Directory where output figures will be saved.
#' @param remove_zeroes Logical. If TRUE, zero values will be removed from the
#' raster and counts.
#' @param aggregate_factor Numeric. Factor by which to aggregate the raster
#' resolution.
#' @param force_overwrite Logical. If TRUE, existing files will be overwritten.
#' @param value_column Character. Name of the column in counts_df representing
#' raster values. Default is "value".
#' @param count_column Character. Name of the column in counts_df representing
#'  counts. Default is "count".
#'
#' @return Saves PNG files to the specified output directory. No return value.
#' @export
generate_polygon_figures <- function(raster, polygons, counts_df,
                                     reference_polygon = NULL,
                                     output_dir = "polygon_figures",
                                     remove_zeroes = FALSE,
                                     aggregate_factor = 1,
                                     force_overwrite = FALSE,
                                     value_column = "value",
                                     count_column = "count") {

  if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

  if (remove_zeroes) {
    raster <- terra::clamp(raster, lower = 1, values = FALSE)
    counts_df <- counts_df |> dplyr::filter(.data[[value_column]] != "0")
  }

  if (aggregate_factor > 1) {
    raster <- terra::aggregate(raster, fact = aggregate_factor, fun = mean, expand = TRUE)
  }

  layer_name <- names(raster)[1]
  raster_crs <- terra::crs(raster)

  polygons_sf <- sf::st_as_sf(polygons)
  if (!is.null(reference_polygon)) {
    reference_sf <- sf::st_as_sf(reference_polygon)
  }

  # Detect shared ID column
  id_col <- dplyr::intersect(names(polygons_sf), names(counts_df))[1]
  if (is.null(id_col)) stop("No shared ID column found between polygons and counts_df.")

  # Standardize counts_df column names
  counts_df <- counts_df |> dplyr::rename(Value = !!sym(value_column), Count = !!sym(count_column))

  # Compute stats
  DT <- as.data.table(counts_df)
  DT[, Value := as.numeric(Value)]
  DT[, Count := as.numeric(Count)]
  stats_df <- DT[, {
    total <- sum(Count, na.rm = TRUE)
    min_val <- if (total > 0) min(Value[Count > 0], na.rm = TRUE) else NA_real_
    max_val <- if (total > 0) max(Value[Count > 0], na.rm = TRUE) else NA_real_
    mean_val <- if (total > 0) sum(Value * Count, na.rm = TRUE) / total else NA_real_
    pct_zero <- if (total > 0) sum(Count[Value == 0], na.rm = TRUE) / total else NA_real_
    q <- stats::approx(cumsum(Count) / total, Value, xout = c(0.25, 0.5, 0.75), rule = 2)$y
    list(n_pixels = total, min = min_val, max = max_val, mean = mean_val,
         PercentPixelsZero = pct_zero, q25 = q[1], q50 = q[2], q75 = q[3])
  }, by = id_col]

  for (poly_id in unique(polygons_sf[[id_col]])) {
    safe_name <- stringr::str_replace_all(as.character(poly_id), "[^A-Za-z0-9_\\-]", "_")
    out_file <- file.path(output_dir, paste0("polygon_", safe_name,
                                             if (remove_zeroes) "_ZeroesRemoved", ".png"))

    if (file.exists(out_file) && !force_overwrite && file.info(out_file)$size > 0) next

    poly <- polygons_sf |> dplyr::filter(as.character(.data[[id_col]]) == as.character(poly_id))
    if (nrow(poly) < 1) next

    if (!st_crs(poly) == raster_crs) poly <- sf::st_transform(poly, raster_crs)
    poly_vect <- terra::vect(poly)

    r_crop <- try(terra::crop(raster, poly_vect), silent = TRUE)
    r_mask <- try(terra::mask(r_crop, poly_vect), silent = TRUE)
    if (inherits(r_crop, "try-error") || inherits(r_mask, "try-error")) next

    df_r <- as.data.frame(r_mask, xy = TRUE, na.rm = FALSE)
    value_col <- names(df_r)[3]
    df_r_non_na <- df_r |> dplyr::filter(!is.na(.data[[value_col]]))

    # Main map
    base_map <- ggplot2::ggplot() +
      { if (nrow(df_r_non_na) > 0)
        ggplot2::geom_raster(data = df_r_non_na, aes(x = x, y = y, fill = .data[[value_col]])) } +
      ggplot2::geom_sf(data = poly, fill = NA, color = "black", size = 0.4) +
      ggplot2::scale_fill_viridis_c(name = layer_name, na.value = "transparent") +
      ggplot2::coord_sf() +
      ggplot2::theme_minimal() +
      ggplot2::labs(title = paste("Raster Map:", poly_id))

    # Optional inset map
    if (!is.null(reference_polygon)) {
      if (!sf::st_crs(reference_sf) == sf::st_crs(poly)) {
        reference_sf <- sf::st_transform(reference_sf, st_crs(poly))
      }

      inset_map <- ggplot2::ggplot() +
        ggplot2::geom_sf(data = reference_sf, fill = "grey85", color = NA) +
        ggplot2::geom_sf(data = poly, fill = "red", color = NA) +
        ggplot2::theme_void()

      map_plot <- cowplot::ggdraw() +
        cowplot::draw_plot(base_map) +
        cowplot::draw_plot(inset_map, x = .75, y = .75, width = .2, height = .2)
    } else {
      map_plot <- base_map
    }

    # Histogram
    hist_data <- counts_df |> dplyr::filter(as.character(.data[[id_col]]) == as.character(poly_id))
    hist_plot <- if (nrow(hist_data) > 0) {
      hist_data |>
        dplyr::mutate(BinStart = floor(Value / 10) * 10) |>
        dplyr::group_by(BinStart) |>
        dplyr::summarise(Count = sum(Count, na.rm = TRUE)) |>
        ggplot2::ggplot(aes(x = BinStart, y = Count)) +
        ggplot2::geom_col(width = 9, fill = "steelblue") +
        ggplot2::theme_minimal() +
        ggplot2::labs(x = layer_name, y = "Count", title = paste("Histogram:", poly_id))
    } else {
      ggplot2::ggplot(df_r_non_na, aes(x = .data[[value_col]])) +
        ggplot2::geom_histogram(binwidth = 10, fill = "steelblue", color = "white") +
        ggplot2::theme_minimal() +
        ggplot2::labs(title = paste("Histogram:", poly_id), x = layer_name, y = "Count")
    }

    # Stats
    stats_row <- stats_df |> dplyr::filter(as.character(.data[[id_col]]) == as.character(poly_id))
    stats_text <- if (nrow(stats_row) > 0) {
      sprintf("Min: %.2f, Mean: %.2f, Max: %.2f\n25th: %.2f, Median: %.2f, 75th: %.2f\nProportion Zero: %.2f",
              stats_row$min, stats_row$mean, stats_row$max,
              stats_row$q25, stats_row$q50, stats_row$q75,
              stats_row$PercentPixelsZero)
    } else {
      "No stats available"
    }

    stats_plot <- ggplot2::ggplot() +
      ggplot2::annotate("text", x = 0, y = 1, label = stats_text, hjust = 0, vjust = 1, size = 3.5) +
      ggplot2::theme_void() +
      ggplot2::labs(title = "Region Stats")

    combined <- (hist_plot) | (map_plot / stats_plot + patchwork::plot_layout(heights = c(3, 1)))
    combined <- combined + patchwork::plot_annotation(title = paste("Polygon:", poly_id,
                                                         if (remove_zeroes) "(Zeroes Removed)" else ""))

    ggplot2::ggsave(filename = out_file, plot = combined, width = 12, height = 7.5, dpi = 300)
  }

  message("All done. Figures are in the folder: ", normalizePath(output_dir))
}
