utils::globalVariables(c("geometry", "id_col", "count", "RegionID", "bin", ".data"))

#' Calculate Raster Value Counts by Polygon
#'
#' Iteratively calculates the frequency of raster values within each polygon.
#' Supports user-provided polygons or automatic retrieval of ecoregions/ecozones.
#'
#' @param raster A `SpatRaster` object.
#' @param polygons Optional. A `SpatVector` or `sf` object of polygons.
#' @param polygon_id Optional. Name of the column in `polygons` to use as polygon ID.
#' @param region_type Optional. `"ecoregion"` or `"ecozone"` if `polygons` is not provided.
#' @param region_ids Optional. Vector of region IDs to filter.
#' @param output_csv Path to save the output CSV file. Default is `"raster_counts.csv"`.
#'
#' @return A `data.frame` with columns: `RegionID`, `value`, `count`.
#' @export
calculate_raster_counts <- function(raster, polygons = NULL, polygon_id = NULL,
                                    region_type = "ecoregion", region_ids = NULL,
                                    output_csv = "raster_counts.csv") {
  if (!inherits(raster, "SpatRaster")) stop("Input raster must be a terra::SpatRaster object.")

  # Load polygons if not provided
  if (is.null(polygons)) {
    if (is.null(region_type)) stop("Either 'polygons' or 'region_type' must be provided.")
    if (!region_type %in% c("ecoregion", "ecozone")) stop("region_type must be 'ecoregion' or 'ecozone'.")

    url <- if (region_type == "ecoregion") {
      "https://sis.agr.gc.ca/cansis/nsdb/ecostrat/district/ecodistrict_shp.zip"
    } else {
      "https://sis.agr.gc.ca/cansis/nsdb/ecostrat/zone/ecozone_shp.zip"
    }

    shp <- reproducible::prepInputs(url = url, destinationPath = tempdir())
    shp <- sf::st_make_valid(shp)

    if(is.null(polygon_id)) {
      polygon_id <- if (region_type == "ecoregion") "ECOREGION" else "ZONE_NAME"
    }

    shp <- shp |>
      dplyr::group_by(.data[[polygon_id]]) |>
      dplyr::summarise(geometry = sf::st_union(geometry), .groups = "drop")

    if (!is.null(region_ids)) {
      shp <- dplyr::filter(shp, .data[[polygon_id]] %in% region_ids)
    }

    shp <- sf::st_transform(shp, st_crs(raster))
    polygons <- terra::vect(shp)
    polygon_id <- id_col
  }

  out_dt <- data.table::data.table(RegionID = character(), value = numeric(), count = integer())

  for (i in seq_along(polygons)) {
    poly <- polygons[i]
    region_val <- poly[[polygon_id]]
    message("Calculating value counts for polygon: ", region_val)

    # Check if polygon overlaps raster extent
    if (is.null(terra::relate(poly, raster, relation = "intersects"))) {
      message("Skipping ", region_val, " (no spatial intersection)")
      next
    }

    r_sub <- try(terra::crop(raster, poly), silent = TRUE)
    if (inherits(r_sub, "try-error")) next
    r_masked <- try(terra::mask(r_sub, poly), silent = TRUE)
    if (inherits(r_masked, "try-error")) next

    vals <- terra::values(r_masked)
    vals <- vals[!is.na(vals)]

    if (length(vals) == 0) next

    val_counts <- data.table::as.data.table(table(vals))
    data.table::setnames(val_counts, c("value", "count"))
    val_counts[, value := as.numeric(value)]
    val_counts[, count := as.numeric(count)]
    val_counts[, RegionID := region_val]
    data.table::setcolorder(val_counts, c("RegionID", "value", "count"))

    out_dt <- data.table::rbindlist(list(out_dt, val_counts))
    gc()
  }

  data.table::fwrite(out_dt, output_csv)
  return(out_dt)
}

#' Plot Raster Statistics and Maps by Polygon
#'
#' This function calculates and returns statistics (min, max, median, mean,
#' 25th percentile, 75th percentile, and proportion of zeroes) for a raster,
#' and creates and saves figures for each polygon in a vector layer, including
#' a histogram of raster values, a map of raster values within the polygon, and
#' a summary of statistics . Optionally, zero values can be removed from the
#' analysis, and the raster can be aggregated to a lower resolution to speed up plotting.
#'
#' @param raster A `SpatRaster` object. The raster containing values to be summarized.
#' @param polygons Optional. A `SpatVector` or `sf` object of polygons to subset the raster. Defaults to Canadian Ecoregions.
#' @param polygon_id Name of the column in `polygons` to use as polygon ID.
#' @param region_type Optional. `"ecoregion"` or `"ecozone"` if `polygons` is not provided.
#' @param region_ids Optional. Vector of region IDs to filter.
#' @param counts_df Optional. A `data.frame` with precomputed counts (`RegionID`, `value`, `count`),
#' such as generated by `terra::extract()`. Polygon ID must match that from polygons.
#' If provided, the function will use these values and skip calculating counts.
#' @param aggregate_factor Optional. Integer factor to aggregate raster for plotting. Default is `1` (no aggregation).
#' @param remove_zeros Logical. Removes zeroes from raster and counts for plotting.
#' Useful to eliminate non-forested areas from forest rasters.
#' @param raster_label Optional. Character label for raster used in plots. Defaults to raster layer name.
#' @param inset.Canada Logical. Generates a small inset map of plotted polygons within Canada. Default to TRUE.
#' @param bin_width Numeric. Bin size for histogram plots. Defaults to 10.
#' @param output_dir Directory to save figures. Default is `"raster_figures"`.
#' @param stats_csv Path to save the statistics CSV. Default is `"raster_stats.csv"`.
#'
#' @return A `data.frame` of computed statistics.
#' @export
plot_raster_statistics <- function(raster, polygons = NULL, polygon_id = NULL,
                                   region_type = "ecoregion", region_ids = NULL,
                                   counts_df = NULL, aggregate_factor = 1,
                                   remove_zeros = FALSE, raster_label = NULL,
                                   inset.Canada = TRUE, bin_width = 10,
                                   output_dir = "raster_figures",
                                   stats_csv = "raster_stats.csv") {
  if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

  layer_name <- names(raster)[1]
  if (is.null(raster_label)) raster_label <- layer_name

  if(is.null(polygon_id)) {
    if(is.null(polygons)) {
      if(region_type == "ecoregion") {
        polygon_id <- "ECOREGION"
      } else if (region_type == "ecozone") {
        polygon_id <- "ZONE_NAME"
      }
    } else(
      stop("If supplying polygons, polygon_id must be be provided")
    )
  }

  if(!is.null(polygons)) {
    polygons <- polygons |>
      dplyr::group_by(.data[[polygon_id]]) |>
      dplyr::summarise(geometry = sf::st_union(geometry), .groups = "drop")

    if (!is.null(region_ids)) polygons <- dplyr::filter(polygons, .data[[polygon_id]] %in% region_ids)
  }

  if (is.null(polygons)) {
    if (!region_type %in% c("ecoregion", "ecozone")) stop("region_type must be 'ecoregion' or 'ecozone'.")

    url <- if (region_type == "ecoregion") {
      "https://sis.agr.gc.ca/cansis/nsdb/ecostrat/district/ecodistrict_shp.zip"
    } else {
      "https://sis.agr.gc.ca/cansis/nsdb/ecostrat/zone/ecozone_shp.zip"
    }

    polygons <- reproducible::prepInputs(url = url, destinationPath = tempdir())
    polygons <- sf::st_make_valid(polygons)

    polygons <- polygons |>
      dplyr::group_by(.data[[polygon_id]]) |>
      dplyr::summarise(geometry = sf::st_union(geometry), .groups = "drop")

    if (!is.null(region_ids)) polygons <- dplyr::filter(polygons, .data[[polygon_id]] %in% region_ids)
  }

  if (inherits(polygons, "SpatVector")) {
    polygons <- terra::project(polygons, crs(raster))
  } else if (inherits(polygons, "sf")) {
    polygons <- sf::st_transform(polygons, st_crs(raster))
  } else (
    stop("Object is neither a SpatVector nor an sf object.")
  )

  poly_sf <- polygons
  polygons <- terra::vect(polygons)

  # If counts_df is missing, generate it
  if (is.null(counts_df)) {
    message("Generating counts using calculate_raster_counts()...")
    counts_df <- calculate_raster_counts(raster = raster,
                                         polygons = polygons,
                                         polygon_id = polygon_id,
                                         region_type = region_type,
                                         region_ids = region_ids) |>
      Cache()
  }

  if (remove_zeros) {
    counts_df <- counts_df[counts_df$value > 0, ]
  }
  # Aggregate raster for plotting
  raster_plot <- if (aggregate_factor > 1) terra::aggregate(raster, fact = aggregate_factor) else raster

  # Remove zeros if requested
  if (remove_zeros) {
    raster_plot <- terra::clamp(raster_plot, lower = 1, value = FALSE)
    raster <- terra::clamp(raster, lower = 1, value = FALSE)  # also clamp original raster for consistency
  }

  # Canada outline for inset
  canada <- reproducible::prepInputs(
    url = "https://www12.statcan.gc.ca/census-recensement/2021/geo/sip-pis/boundary-limites/files-fichiers/lpr_000b21a_e.zip",
    destinationPath = "inputs",
    fun = "terra::vect"
  )
  canada <- terra::project(canada, raster)
  canada_sf <- sf::st_as_sf(canada)

  stats_list <- list()

  for (i in seq_len(nrow(poly_sf))) {
    region_val <- poly_sf[[polygon_id]][i]
    label_prefix <- if (!is.null(region_type)) {
      if (region_type == "ecoregion") "Polygon "
      else if (region_type == "ecozone") "Ecozone "
      else paste0(polygon_id, ": ")
    } else paste0(polygon_id, ": ")
    region_label <- paste0(label_prefix, region_val)

    message("Plotting polygon:", region_label)

    poly <- poly_sf[i, ]
    poly_spat <- terra::vect(poly)

    # Skip if polygon doesn't intersect raster extent
    if (!terra::relate(poly_spat, raster, relation = "intersects")) {
      message("Skipping ", region_label, " (no spatial intersection)")
      next
    }

    # Filter counts_df for this polygon
    poly_counts <- counts_df[counts_df$RegionID == region_val, ]
    poly_counts$value <- as.numeric(poly_counts$value)
    poly_counts$count <- as.numeric(poly_counts$count)

    # Skip if no valid data or only one unique value
    if (nrow(poly_counts) == 0 || length(unique(poly_counts$value)) < 2) {
      message("Insufficient data for ", region_label, "; skipping.")
      next
    }


    # Compute stats from counts_df
    total <- sum(poly_counts$count)
    weighted_quantile <- function(x, w, probs = c(0.25, 0.5, 0.75)) {
      if (length(x) == 0 || length(w) == 0 || sum(w) == 0) return(rep(NA_real_, length(probs)))
      ord <- order(x); x <- x[ord]; w <- w[ord]
      cumw <- cumsum(w) / sum(w)
      stats::approx(x = cumw, y = x, xout = probs)$y
    }
    q <- weighted_quantile(poly_counts$value, poly_counts$count)
    stats <- data.frame(RegionID = region_val,
                        min = min(poly_counts$value), mean = sum(poly_counts$value * poly_counts$count) / total,
                        max = max(poly_counts$value), q25 = q[1], q50 = q[2], q75 = q[3],
                        PercentPixelsZero = sum(poly_counts$count[poly_counts$value == 0]) / total)
    stats_list[[i]] <- stats

    # Crop aggregated raster for plotting
    r_mask <- terra::mask(terra::crop(raster_plot, poly_spat), poly_spat)

    # Skip if raster is empty (all NA)
    if (all(is.na(terra::values(r_mask)))) {
      message("Skipping ", region_label, " (raster empty after crop)")
      next
    }

    map_df <- as.data.frame(r_mask, xy = TRUE, na.rm = TRUE)
    value_col <- names(map_df)[3]

    # Histogram from counts_df
    poly_counts_binned <- poly_counts |>
      dplyr::mutate(bin = floor(value / bin_width) * bin_width) |>
      dplyr::group_by(bin) |>
      dplyr::summarise(count = sum(count), .groups = "drop")
    hist_plot <- ggplot2::ggplot(poly_counts_binned, ggplot2::aes(x = bin, y = count)) +
      ggplot2::geom_col(fill = "steelblue") +
      ggplot2::theme_minimal() +
      ggplot2::labs(title = paste("Histogram:", region_label), x = raster_label, y = "Count")

    # Main map
    map_plot_base <- ggplot2::ggplot() +
      ggplot2::geom_raster(data = map_df, ggplot2::aes(x = x, y = y, fill = .data[[value_col]])) +
      ggplot2::geom_sf(data = poly, fill = NA, color = "black") +
      ggplot2::scale_fill_viridis_c(name = raster_label) +
      ggplot2::theme_minimal() +
      ggplot2::labs(title = paste("Map:", region_label))

    if(inset.Canada == TRUE) {
      # Inset map
      inset_plot <- ggplot2::ggplot() +
        ggplot2::geom_sf(data = canada_sf, fill = "grey85", color = NA) +
        ggplot2::geom_sf(data = poly, fill = "red", color = NA) +
        ggplot2::theme_void()
      map_with_inset <- cowplot::ggdraw() +
        cowplot::draw_plot(map_plot_base) +
        cowplot::draw_plot(inset_plot, x = 0.75, y = 0.75, width = 0.2, height = 0.2)
    }

    # Stats plot (centered text)
    stats_text <- paste0("Min: ", round(stats$min, 2),
                         " Mean: ", round(stats$mean, 2),
                         " Max: ", round(stats$max, 2), "\n",
                         "25%: ", round(stats$q25, 2),
                         " Median: ", round(stats$q50, 2),
                         " 75%: ", round(stats$q75, 2),
                         " % Zero: ", round(stats$PercentPixelsZero * 100, 2), "%")
    stats_plot <- ggplot2::ggplot() +
      ggplot2::annotate("text", x = 0.5, y = 0.5, label = stats_text, hjust = 0.5, vjust = 0.5) +
      ggplot2::theme_void() +
      ggplot2::labs(title = "Statistics")

    if(inset.Canada == TRUE) {
      combined <- hist_plot | (map_with_inset / stats_plot + patchwork::plot_layout(heights = c(3, 1))) +
        patchwork::plot_annotation(title = region_label)
    } else {
      combined <- hist_plot | (map_plot_base / stats_plot + patchwork::plot_layout(heights = c(3, 1))) +
        patchwork::plot_annotation(title = region_label)
    }
    fig_name <- paste0("region_", stringr::str_replace_all(region_val, "[^A-Za-z0-9]", "_"), ".png")
    ggplot2::ggsave(filename = file.path(output_dir, fig_name), plot = combined, width = 12, height = 7.5, dpi = 300)
  }

  stats_df <- dplyr::bind_rows(stats_list)
  utils::write.csv(stats_df, file.path(output_dir, stats_csv), row.names = FALSE)
  return(stats_df)
}
